language: go
go:
  - 1.14.7
services:
  - docker
  - postgresql
env:
  global:
    - DOCKER_USER=dinopuguh
    - MYCAP_DB_USER=postgres
    - MYCAP_DB_PASSWORD=postgres
    - MYCAP_DB_HOST=localhost
    - MYCAP_DB_NAME=mycap
    - MYCAP_DB_PORT=5432
    - secure: ggKqLcD5pRzOhkQKTx+Oeb8jFK6TlNgYJpNdEY8CA9O6H7EWyJ50hPJxVqz2rLjNQrIiVf0+XPA2+17cWizFPi9qdWcIXj6rJkbMYYLWChEXVki7crsstAssvdX+rfHgwAPSFJ4gIr6LFxh/9KUEv13V11ZReEg40K2UIRJd+WhQxXoaU3xJNEjbiLpTPDyxK3zLdbPLFBfuzC3HOONFubFr5LDy8uRVPMwEL9KzTWReSN+YDLY/BoVSWAS8z2hW4FvLoYU1irHFcvvEg1c/ysbwwrHf4/A/nDouK2DQU294h2bsX7Q9CCRS3HgcW+KaZaOsS1SI4Y48CT1uCPElLKG/zYJLDCeTEcu4B9yk+YSzpx+D+bY4sxV51Z/1j86a/j7Er4Atv8gfC0Uh5NnoOigno0RGqSUx4KuRoXl1yO2wR6ix2fqjDYa5ZFz55p/Lrx3xIVghRf3s+trelZRp+qvyiCFljURvtCkTZiGEeFVQQjDxdLp8dUkf7EKUX3PlUfNBddWqjg0hfRUSnI5y3OhxUUQKjXM1cUY4wXJQJoMwrN3+ePJsGdRNkFiSusskPufhE/vWpGOpbM4eewnsVTcMwSKMNQVx81O1W0JsieOnrRm0B+4ln7nuecwoO/owhYTkoWpKLAWX1na69STuLx+oUS5y8q8bL2Tn5VjEVVA=
    - secure: BNdiUkPhkto14CdG3Tjr0JoJv7IQNtdk68DCgAgSHnbqVzOW5lAlbG9hz3J/GkGvONzfzQHanLxpIPQhQhd0ETv6WDaOE5UwoHg6xoSHPF4m+Ifw3cUp+ksS0R7x9J+1Zd5iIk35aEClsqE/x1tFHkW+bq75ljRERt0mCX+nP0GWN96SZDgmOVBs8sN1xCUgpzDN3oUGDo4icsdZAKXTW8MgEQCmYzwd3Xds8IUMKpshf39shJLKV1EfNcNRCntlmJoWn2Et52OdMvYbgAd/xsPi4HxRlhOnxEAFS6J6BnP1y1/mLouRUHa8iFg6iu+jWJA6rxgh1GM+rDcVjChzPa8lcEbHymkf1WDqb4KEeCItEd9MhDl2JDL4eWaNws0B5n71AuRpRgUZdwFDsnKrmZpUJRvImLgozbBWZAv+MiGzNcqkS9r5mhRIfIGW+RNYTh8lN1GFO8QT9f8P4Q9aHeuscgUYJIi/LoSnrpC5N8fMNJtQgKsBTUzUQwK+/yGPneWrNTDghRVnC43IKLb+0RQCNjj//z0hjEbvRll9IpnVUeStHUBJVAW6E34Tv1MjLcW7+VQ3OAJK5w4I2wdbDGkRjhdkf9qYYX2O+YikwKsJug+OZizVppRWsQuxGPcLeiBLzmf4YzGIvfSCCXeHYJwV802iZJqxn+FIOKJPLsI=
    - secure: CX2T2/VT4mXLs4w+ev8A0PSPUeynPCfY9YcuEkQ2db9bkhwDscYLI4VT+PEu/c7Uxs+edL2zarsow8O5/tEv6BterrFI+JfjRKWOOviTu/BOxEkyjBcnabskIHIsLahgWpZ11b2wQJPUe5W9h3MQMh+9GEHbEX93/h/ZBmE6sN/a6SvTLjTkLKJbdDMVvpqtBwqoEtEbQMNqkPYZTxfT1d0G8xfpXSXkl1dakQsqS1c2QSrVO9qs4h58W1crI7d+1LGqc/WhqrZ7dqlHDxoUQ+7BNk0jhUXc85ErZQ8jEUt7ljxSbd1q6bdzqL0a9erfcvf4i2cupCqtCp4G9dmlJ2QkZqZpRSb/VDDG086HuhEK1+KrR5HQNNrCGRq2s8SiJopMfDzJI2dbh1zaJc+fXwH00z/jouPugBiqNxp0/pKAug8fWHFswm5uXReaYHlN6uvxHA4jTBa1saK/7pblopli0XNZ1zw3VRenvBTsuus15cc5xmFJ7lXEOgMS1PGoJ5jmoMFiIFqkU1M3vplp546033WDxXcSmeN65nesJVLzb9bwBMhVrL0ZSyoWv8QCEnL6vJmDXKnp4dWoPjuZbfJ3NcT+YJeOTQZ/M+p7RMhRjLBmFJG8XzWITd9z5+uLPDs+vV6+RY7Q3mmDCja+CZguEqMilUIZMMA24vwg9hQ=
    - secure: tMV7Hus9xudn1CM9wnCO2Tlt6CL0c8kypwz6jfnSfEvopWusLJdTr5zeoMgyr+ElJ4Gac/9Hsbm6J1e299uo6O3i86XMhxmp0RZXMShpNs5RgrJ3yoPG5N3/sROCXJ8lP3RaQ8/GDxrQ6rL0FBfSnBH3Jcg9PrV+pb28h7uhIqXP0ADRxQeOiCx1rkF1g74lt8KE8Jh/f5hXeBIB2scB6ZV5zBzvdBLDOZObxONRor6rRNJVNz2AKAixEfXgpniABZ3vtedfDnfsxUAHg0cgZOFZRaOc7XHEPAjAQwCKIOMCtm7itpdRENfJc0yQ7RfyuY9JKjGuqSX7a1pP7GBocLgo3bwBq80hQdJqpjeAOj2uqms3o5x9XOxMCb0X+v4TDRbfsKyXbjio7B+LZpXkVYMD7JrdndMq4hgO1bPUZREsbq1TeNayiTr57qCVOyNmXcdMTUvWOk8xizj8Sq7MfXAFOe1qjbTsKomSNz927qKCIC8PdhvAWhIQsmI24NmHhEeaEQVlHuFl2aIpM/gpKQlY5b7EtMbxfXYDiD0yLV5pPl4561Lf4RZcDtDr+f3irAR50QyYSb1R4hiRk7yRv6XsineTwYLOnKU7RJowXP/I5umnzKcqAyewaOv6RiD/m6/pTbDIxMG3+ACN/UC13BPpupQlNSGEvGuZcF+4M80=
before_script:
  - psql -c 'create database mycap;' -U postgres
script:
  - scripts/cibuild.sh
after_success:
  - docker build -t mycap-backend .
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag mycap-backend $DOCKER_USER/mycap-backend:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/mycap-backend:$TRAVIS_BUILD_NUMBER
  - docker tag mycap-backend $DOCKER_USER/mycap-backend:latest
  - docker push $DOCKER_USER/mycap-backend:latest
deploy:
  provider: heroku
  api_key:
    secure: FrOMlK0AbBh6JuGO2N8vw8fufISpe4tOUYJmPeTfwxWbKCN2Bd54eoaQQ2mzO4SmE02kepgETd4Yl073taCIY8mwPckRTshCoXm91fKw88G328NFA6QmaTyOh8K0DMVxOstgkd/EXoMOY0BmugvDEw2C5xtZ3RL0FYHZQf7e00UGgNlzGNAk4FVa7NvkNIpZG/im8Wpi/Ai7CmVHf5t48wNdYWRPmw9/ZP2WxxLj0gKVcMNPKlzs01mMis9JjVR8HvU8cz0nHAB5pyZmZAnYUI07QNBspnSKH4CbWyft5e9p6xfsZYMKGKaO+5GPasdK+2kUly5RDhj5qQOebHA4OO+eMiiYLa8JKl3nD4k5YFrmDgNsEZSv5OBLFNAjoFmoc8j9D8w1Z1tnohuyUAJwTPhUPxNS0YhgXdzlTs9g+kKZ6rDb0bTXcaxNFlcXB/T0mFDpXqLEibYjZm6qI/XmLogOe3zEoGjlWopmfsovVHoVTKlFxrY8EylOgPD+yLITxxDAxyou8EXP9zSQIlgtOQj6wdcxVgKJ5WnSiCtzWoDKF8TreevgnvY19nwIkbB9PnfICOPkZDrL1G7hqndQaPpXsFaZ+2Tbt06JQqHQ616C8ymbnT6FtCkLm2HYtozWpC5g9der5q/eu6GEhU2c8W+ycPYLet+/DTKjUaEdN1M=
  app:
    master: mycap-staging
