version: "3.8"
services:
  postgres_db:
    image: postgres:9.6.18-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_PORT}
    ports:
      - 5432:5432
    volumes:
      - mycap-volume:/var/lib/postgresql/data
    networks:
      - mycap-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYCAP_DB_USER=postgres
      - MYCAP_DB_PASSWORD=postgres
      - MYCAP_DB_HOST=postgres_db
      - MYCAP_DB_NAME=mycap
      - MYCAP_DB_PORT=5432
      - MYCAP_JWT_TOKEN=v3rys3cr3tt0k3n
    ports:
      - 3000:3000
    depends_on:
      - postgres_db
    networks:
      - mycap-network

volumes:
  mycap-volume:
    name: mycap-volume

networks:
  mycap-network:
    name: mycap-network
