#!/usr/bin/env bash
# Usage: scripts/gocover
#
# Coverage test

set -e

echo "mode: count" > coverage.out
for Dir in $(find ./* -maxdepth 10 -type d);
do
    if ls $Dir/*.go &> /dev/null;
    then
        go test -v -coverprofile=profile.out $Dir
        if [ -f profile.out ]
        then
            cat profile.out | grep -v "mode: count" >> coverage.out
        fi
    fi
done

$GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-pro -repotoken $COVERALLS_TOKEN

rm -rf ./coverage.out
rm -rf ./profile.out