basePath: /api
definitions:
  group.CreateGroup:
    properties:
      type:
        type: string
    type: object
  group.Group:
    properties:
      admin:
        $ref: '#/definitions/user.User'
        type: object
      admin_id:
        type: integer
      admin_username:
        type: string
      participants:
        items:
          $ref: '#/definitions/user.User'
        type: array
      type:
        type: string
    type: object
  group.JoinGroup:
    properties:
      admin_username:
        type: string
    type: object
  group.LeaveGroup:
    properties:
      admin_username:
        type: string
      remaining_time:
        type: integer
    type: object
  response.HTTP:
    properties:
      data:
        type: object
      message:
        type: string
      status:
        type: integer
      success:
        type: boolean
    type: object
  user.LoginUser:
    properties:
      email:
        example: dinopuguh@mycap.com
        type: string
      password:
        example: s3cr3tp45sw0rd
        type: string
    type: object
  user.RegisterUser:
    properties:
      email:
        example: dinopuguh@mycap.com
        type: string
      name:
        example: Dino Puguh
        type: string
      password:
        example: s3cr3tp45sw0rd
        type: string
      type_id:
        description: '(1: Free, 2: Premium, 3: Pro)'
        example: 1
        type: integer
      username:
        example: dinopuguh
        type: string
    type: object
  user.ResponseAuth:
    properties:
      access_token:
        type: string
      user:
        $ref: '#/definitions/user.User'
        type: object
    type: object
  user.Type:
    properties:
      name:
        type: string
    type: object
  user.UpdateUser:
    properties:
      name:
        example: Dino Puguh
        type: string
      reached_time_limit:
        example: false
        type: boolean
      remaining_time:
        example: 1800
        type: integer
      type_id:
        description: '(1: Free, 2: Premium, 3: Pro)'
        example: 2
        type: integer
    type: object
  user.User:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      reached_time_limit:
        type: boolean
      remaining_time:
        type: integer
      type:
        $ref: '#/definitions/user.Type'
        type: object
      type_id:
        type: integer
      username:
        type: string
    type: object
info:
  contact:
    email: dinopuguh@gmail.com
    name: Dino Puguh
  description: This is an API for MyCap Application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: MyCap API
  version: "1.0"
paths:
  /v1/groups:
    get:
      consumes:
      - application/json
      description: Get all groups
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.HTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/group.Group'
                  type: array
              type: object
      summary: Get all groups
      tags:
      - groups
    post:
      consumes:
      - application/json
      description: Create a group chat or conference
      parameters:
      - description: Create group
        in: body
        name: group
        required: true
        schema:
          $ref: '#/definitions/group.CreateGroup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.HTTP'
            - properties:
                data:
                  $ref: '#/definitions/group.Group'
              type: object
      security:
      - ApiKeyAuth: []
      summary: Create a group chat or conference
      tags:
      - groups
  /v1/join-groups:
    post:
      consumes:
      - application/json
      description: Joining group chat or conference
      parameters:
      - description: Join group
        in: body
        name: group
        required: true
        schema:
          $ref: '#/definitions/group.JoinGroup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.HTTP'
            - properties:
                data:
                  $ref: '#/definitions/group.Group'
              type: object
      security:
      - ApiKeyAuth: []
      summary: Joining group chat or conference
      tags:
      - groups
  /v1/leave-groups:
    post:
      consumes:
      - application/json
      description: Leaving group chat or conference
      parameters:
      - description: Leave group
        in: body
        name: group
        required: true
        schema:
          $ref: '#/definitions/group.LeaveGroup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.HTTP'
            - properties:
                data:
                  $ref: '#/definitions/group.Group'
              type: object
      security:
      - ApiKeyAuth: []
      summary: Leaving group chat or conference
      tags:
      - groups
  /v1/login:
    post:
      consumes:
      - application/json
      description: User login
      parameters:
      - description: User login
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.LoginUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.HTTP'
            - properties:
                data:
                  $ref: '#/definitions/user.ResponseAuth'
              type: object
      summary: User login
      tags:
      - auth
  /v1/register:
    post:
      consumes:
      - application/json
      description: Register user
      parameters:
      - description: Register user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.RegisterUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.HTTP'
            - properties:
                data:
                  $ref: '#/definitions/user.ResponseAuth'
              type: object
      summary: Register a new user
      tags:
      - auth
  /v1/users:
    get:
      consumes:
      - application/json
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.HTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/user.User'
                  type: array
              type: object
      summary: Get all users
      tags:
      - users
  /v1/users/{id}:
    delete:
      consumes:
      - application/json
      description: Remove user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.HTTP'
      security:
      - ApiKeyAuth: []
      summary: Remove user by ID
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.UpdateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.HTTP'
            - properties:
                data:
                  $ref: '#/definitions/user.User'
              type: object
      security:
      - ApiKeyAuth: []
      summary: Update user by ID
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
